server:
  port: 18091

spring:
  application:
    name: openfeign-sentinel

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8847
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8089
      eager: true

management:
  endpoints:
    web:
    exposure:
      include: '*'
feign:
  sentinel:
    enabled: true
