server:
  port: 17081

spring:
  application:
    name: ay-gateway-db
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8847
  #    gateway:
  #      routes:
  #        # 路由id，可以不写，默认是uuid唯一值
  #        - id: example
  #          # 设置路由uri，可以是跳转的url地址，也可以是"lb://serviceId"
  #          uri: lb://service-01
  #          # 路由断言，可配置多个，请求地址包含example，会跳转到example服务
  #          predicates:
  #            - Path=/example/**
  #          filters:
  #            - AddRequestHeader=X-Request-red, blue
  #        - id: openfeign
  #          # 设置路由uri，可以是跳转的url地址，也可以是"lb://serviceId"
  #          uri: lb://openfeign
  #          # 路由断言，可配置多个，请求地址包含example，会跳转到example服务
  #          predicates:
  #            - Path=/openfeign/**
  #          filters:
  #            - AddRequestHeader=X-Request-red, blue
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring-cloud-gateway
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver


# 端点开启
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true

