server:
  port: 18087

spring:
  application:
    name: hx-auth-01

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8847

management:
  endpoints:
      web:
      exposure:
        include: '*'

