server:
  port: 18081

spring:
  application:
    name: ay-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.38.188:8848
    gateway:
      routes:
        # 路由id，可以不写，默认是uuid唯一值
        - id: example
          # 设置路由uri，可以是跳转的url地址，也可以是"lb://serviceId"
          uri: lb://service-01
          # 路由断言，可配置多个，请求地址包含example，会跳转到example服务
          predicates:
            - Path=/example/**
          filters:
            - AddRequestHeader=X-Request-red, blue

management:
  endpoints:
    web:
      exposure:
        exclude: "*"

