spring:
  application:
    name: zuul-service

server:
  port: 9080

zuul:
  routes:
    blog:
      path: /baidu/**
      url: https://www.baidu.com

management:
  endpoint:
    health:
      show-details: always
    routes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"



