server:
  port: 18081
spring:
  application:
    name: consul-producer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${server.port}