
server:
  port: 18091

spring:
  application:
    name: spring-cloud-bus

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8847
      config:
        server-addr: localhost:8847


management:
  endpoints:
    web:
    exposure:
      include: '*'
