# 指定运行端口
server:
  port: 18103

# 指定服务名称
spring:
  application:
    name: service-consumer

eureka:
  client:
    # 注册到Eureka的注册中心
    register-with-eureka: true
    # 获取注册实例列表
    fetch-registry: true
    service-url:
      # 配置注册中心地址
      defaultZone: http://localhost:8001/eureka

ribbon:
  eureka:
    enabled: true