spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 2181
          zkNodes: localhost
          defaultZkPort: 9092
server:
  port: 18080
