server:
  port: 18091
spring:
  application:
    name: spring-cloud-stream-output

management:
  health:
    binders:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        ##include: "*"
        include: "bindings"
